config/routes.rb
Rails.application.routes.draw do

  resources :questions
  get "projects/home"
  get "projects/about"
  get "ideas/start"
  get "projects/help"
  get "projects/impressum"
  

  devise_for :users
  resources :creativitycards 
  resources :projects 
  resources :ideas 

   

  root 'projects#home'

end

app/models/idea.rb
class Idea < ActiveRecord::Base
	belongs_to :project
	belongs_to :user

	validates_length_of :post, :maximum => 300
	validates :post, :project_id, :user_id, presence: true

	def self.to_csv(options = {})
    CSV.generate(options) do |csv|
      csv << column_names  # hinzufügen von Spaltenbezeichnung zu CSV
      all.each do |ideas|   
        csv << ideas.attributes.values_at(*column_names) #jedes Attribut von der Idee werden die Spaltenbezeichnung zugeordnet
      end
    end
  end
  
end

app/controllers/ideas_controller.rb
class IdeasController < ApplicationController
  before_action :set_idea, only: [:show, :edit, :update, :destroy]
  before_action :set_idea_identification, only: [ :edit, :update, :destroy]
  before_action :authenticate_user!
  # GET /ideas
  # GET /ideas.json
  def start
    #Ausgabe von projekten nach done (done=true oder deadline ist vorbei) 
    #und todo (done=false und deadline noch nicht erreicht ).
    #:sorting gibt die Möglichkeit zu sortieren in View
    if params[:sorting]
      @done = Project.where("done = ? OR deadline < ?", true, Date.today).order(params[:sorting] => :asc)
      @todo = Project.where("done = ? AND deadline >= ?", false, Date.today).order(params[:sorting] => :asc)
    else 
      @done = Project.where("done = ? OR deadline < ?", true, Date.today).order(deadline: :desc)     
      @todo = Project.where("done = ? AND deadline >= ?", false, Date.today).order(deadline: :asc)
    end
  end

  def index
    @ideas = Idea.all
    # Wenn User nicht Admin ist, darf er die Ideenliste nicht ansehen
    if current_user.admin != true
      redirect_to :root, alert: 'Only for Admins!'
    end

    #Export zu csv-Format und Excel-format
    respond_to do |format|
      format.html
      format.csv { send_data @ideas.to_csv }
      format.xls
    end
  end

  # GET /ideas/1
  # GET /ideas/1.json
  def show
  end

  # GET /ideas/new
  def new
    @idea = Idea.new
    #Ausgabe von alle Ideen von User (Eigentümer)
    @useridea = current_user.ideas.all
  end

  # GET /ideas/1/edit
  def edit
  end

  # POST /ideas
  # POST /ideas.json
  def create
    @idea = current_user.ideas.new(idea_params)

    respond_to do |format|
      if @idea.save
        format.html { redirect_to :back, notice: 'Idea was successfully created.' }
        format.json { render :show, status: :created, location: @idea }
      else
        format.html { render :new }
        format.json { render json: @idea.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /ideas/1
  # PATCH/PUT /ideas/1.json
  def update
    respond_to do |format|
      if @idea.update(idea_params)
        format.html { redirect_to @idea, notice: 'Idea was successfully updated.' }
        format.json { render :show, status: :ok, location: @idea }
      else
        format.html { render :edit }
        format.json { render json: @idea.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /ideas/1
  # DELETE /ideas/1.json
  def destroy
    @idea.destroy
    respond_to do |format|
      format.html { redirect_to ideas_url, notice: 'Idea was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_idea
      @idea = Idea.find(params[:id])
    end

    def set_idea_identification
      @idea = Idea.find(params[:id])
      # Nur User (Eigentümer) darf eigen Idee (sucht nach ID) anzeigen
      if @idea.user_id != current_user.id
        redirect_to idea_path, alert: 'You can edit oder delete only your own Ideas.'
      end
    end


    # Never trust parameters from the scary internet, only allow the white list through.
    def idea_params
      params.require(:idea).permit(:post, :project_id, :user_id)
    end
end

app/helpers/ideas_helper.rb
module IdeasHelper
end

app/views/ideas/_form.html.erb
<%= form_for @idea, :html => { :role => "form"} do |f| %>    
  <% if @idea.errors.any? %>
    <div class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@idea.errors.count, "error") %> prohibited this idea from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
          <% @idea.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="form-group">
    <%= f.label :project_id %><br>
    <%= f.select :project_id, Project.all.collect {|c| [ c.name, c.id ] }, { :include_blank => true, :selected => @idea.project_id, :prompt => "bitte Project wählen für das die Idee erstellt wird"}, class: "form-control" %>
  </div> 

  <div class="form-group">
    <%= f.label :post %><br>
    <%= f.text_area :post, :maxlength => 300, class: "form-control", placeholder: "Can't wait for your Idea" %>
  </div>

  <div class="actions">
    <%= f.submit "Save Project", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/ideas/_todoproject.html.erb
<table class="table table-striped table-bordered table-hover "> 
  <thead>
    <tr>
      <th>
      <% if params[:sorting] == "name" %>
        Name
      <% else %>
        <%= link_to "Name", ideas_start_path(sorting: "name") %>
      <% end %>
      </th>
      <th>
      <% if params[:sorting] == "deadline" %>
        Deadline
      <% else %>
        <%= link_to "Deadline", ideas_start_path(sorting: "deadline") %>
      <% end %>
      </th>
      <th>
      <% if params[:sorting] == "question" %>
        Question
      <% else %>
        <%= link_to "question", projects_path(sorting: "question") %>
      <% end %> 
      </th>
    </tr>
  </thead>

  <tbody>
    <% @todo.each do |project| %>
      <tr>
        <td><%= link_to project.name, project_path(id: project.id) %></td>
        <td>
          <%= "in " if !project.is_delayed? %> 
          <%= pluralize(project.distance_from_now_in_days.abs, "Day")  %>
          <%= " ago " if project.is_delayed? %>
          (<%= project.deadline %>) 
        </td>
        <td><%= link_to project.question, project_path(id: project.id) %></td>                   
      </tr>
    <% end %>
  </tbody>
</table>

app/views/ideas/edit.html.erb
<h1>Editing Idea</h1>

<%= render 'form' %>

app/views/ideas/index.html.erb
<div class="bs-docs-section">
  <div class="row">
    <div class="col-md-12">

      <div class="page-header">          
        <h1>All Ideas</h1>
      </div>        

        <div class="well"> 
          <%= link_to 'Export XLS', url_for(:format => 'xls'), class: "btn btn-primary btn-sm" %> 
          <%= link_to 'Export CSV', url_for(:format => 'csv'), class: "btn btn-primary btn-sm" %>
          </br>
          </br>
          <div class="panel panel-info">
            <h3></h3>
            <div class="panel-body"> 
              <div class="table-responsive table-scrollable">      
                <table class="table table-striped table-bordered table-hover ">
                  <thead>
                    <tr>
                      <th>Project ID</th>
                      <th>Name</th>
                      <th>Deadline</th>
                      <th>Done</th>
                      <th>Idea ID</th>
                      <th>Post</th>      
                      <th>User ID</th>
                      <th>Username</th>
                      <th>User-Email</th>
                      <th>Age</th>
                      <th>Sex</th>
                      <th>Nationalität</th>
                      <th>Abschluss</th>
                      <th>Beruf</th>
                      <th>Created_at</th>
                      <th>Updated_at</th>
                      <th colspan="3"></th>

                    </tr>
                  </thead>

                  <tbody>
                    <% @ideas.each do |idea| %>
                      <tr>
                        <td><%= idea.project_id %></td>
                        <td><%= idea.project.name %></td>
                        <td><%= idea.project.deadline %></td>
                        <td><%= idea.project.done %></td>
                        <td><%= idea.id %></td>
                        <td><%= idea.post %></td>
                        <td><%= idea.user_id %></td>
                        <td><%= idea.user.username %></td>
                        <td><%= idea.user.email %></td>
                        <td><%= idea.user.age %></td>
                        <td><%= idea.user.sex %></td>
                        <td><%= idea.user.nationality %></td>
                        <td><%= idea.user.qualification %></td>
                        <td><%= idea.user.profession %></td>
                        <td><%= idea.created_at %></td>
                        <td><%= idea.updated_at %></td>        
                        <td><%= link_to 'Show', idea %></td>
                        <td><%= link_to 'Edit', edit_idea_path(idea) %></td>
                        <td><%= link_to 'Destroy', idea, method: :delete, data: { confirm: 'Are you sure?' } %></td>
                      </tr>
                    <% end %>
                  </tbody>
                </table>
              </div>
            </div>
          </div>
        </div>
      </div>

    </div>
  </div>
</div>

    

app/views/ideas/index.xls.erb
<table >
  <thead>
    <tr>
      <th>Project ID</th>
      <th>Name</th>
      <th>Deadline</th>
      <th>Done</th>
      <th>Idea ID</th>
      <th>Post</th>      
      <th>User ID</th>
      <th>Username</th>
      <th>User-Email</th>
      <th>Age</th>
      <th>Sex</th>
      <th>Nationalität</th>
      <th>Abschluss</th>
      <th>Beruf</th>
      <th>Created_at</th>
      <th>Updated_at</th>
    </tr>
  </thead>

  <tbody>
    <% @ideas.each do |idea| %>
      <tr>
        <td><%= idea.project_id %></td>
        <td><%= idea.project.name %></td>
        <td><%= idea.project.deadline %></td>
        <td><%= idea.project.done %></td>
        <td><%= idea.id %></td>
        <td><%= idea.post %></td>
        <td><%= idea.user_id %></td>
        <td><%= idea.user.username %></td>
        <td><%= idea.user.email %></td>
        <td><%= idea.user.age %></td>
        <td><%= idea.user.sex %></td>
        <td><%= idea.user.nationality %></td>
        <td><%= idea.user.qualification %></td>
        <td><%= idea.user.profession %></td>
        <td><%= idea.created_at %></td>
        <td><%= idea.updated_at %></td> 
      </tr>
    <% end %>
  </tbody>
</table>

app/views/ideas/new.html.erb
<div class="bs-docs-section">
  <div class="row">
    <div class="col-md-12">

      <div class="page-header">          
        <h1>New Idea</h1>
      </div>

      <div class="col-md-3" id="leftCol">
        <div class="well">    
          
        </div>
      </div>     

      <div class="col-md-9" id="rightCol"> 
        <div class="well"> 
          <%= render 'form' %>
        </div>
      </div>

      <div class="col-md-9 col-md-offset-3"> 
        <div class="well"> 
        	<% @useridea.each do |idea| %>
          <div class="panel panel-info">
            <div class="panel-body">      				
      				<p>        
        				<%= idea.post %>
      				</p>     					 
     				</div>
     			</div>
     			<% end %> 
     		</div>
     	</div>  
      

    </div>
  </div>
</div>

app/views/ideas/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Post:</strong>
  <%= @idea.post %>
</p>

<p>
  <strong>Project:</strong>
  <%= @idea.project_id %>
</p>

<p>
  <strong>User:</strong>
  <%= @idea.user_id %>
</p>

<%= link_to 'Edit', edit_idea_path(@idea), class: "btn btn-warning"  %>

app/views/ideas/start.html.erb
<div class="bs-docs-section">
  <div class="row">
    <div class="col-md-12">

      <div class="page-header">          
        <h1>"Using the brain to storm a problem"</br>
          <small>Osborn 1963</small></h1>
      </div>

      <div class="col-md-3" id="leftCol">
        <div class="well">  
          <div class="panel panel-primary">
            <div class="panel-body">  
              <p><strong>Wählen Sie bitte nacheinander die Projekte aus, um Ideen einzugeben.</strong></p>
            </div>
          </div>
        </div>
      </div>     

      <div class="col-md-9" id="rightCol"> 
        <div class="well"> 
          <div class="panel panel-primary">
              <h3>Projects</h3>
            <div class="panel-body">
              <div class="table-responsive table-scrollable">
                <%= render 'todoproject' %>
              </div>
            </div>
          </div>
        </div>
      </div>

    </div>
  </div>
</div>


