config/routes.rb
Rails.application.routes.draw do

  resources :questions
  get "projects/home"
  get "projects/about"
  get "ideas/start"
  get "projects/help"
  get "projects/impressum"
  

  devise_for :users
  resources :creativitycards 
  resources :projects 
  resources :ideas 

   

  root 'projects#home'

end

app/models/project.rb
class Project < ActiveRecord::Base


	belongs_to :user
	has_many :ideas
	has_many :creativitycards

	validates :name, :deadline, :question, presence: true
	validates :name, uniqueness: true

	# benötigt für gem 'nested_form'. Ermöglicht Kreativismenkarten im Proket-Controller zu erzeugen
	accepts_nested_attributes_for :creativitycards, 
  		allow_destroy: true, 
      :reject_if => :all_blank

	def is_delayed?
	 self.deadline < Date.today
	end

	def distance_from_now_in_days
	  (self.deadline - Date.today).to_i     
	end

	def self.to_csv(options = {})
    CSV.generate(options) do |csv|
      csv << column_names
      all.each do |projects|
        csv << projects.attributes.values_at(*column_names)
      end
    end
  end
	
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:show, :edit, :update, :destroy]
  before_action :set_project_admin_edit_destroy, only: [:edit, :update, :destroy]
  before_action :set_project_admin_create, only: [:new, :create]
  before_action :set_user, only: [:help]
  before_action :authenticate_user!, except: [:home, :about, :help, :impressum]

  # GET /projects
  # GET /projects.json
  def home
  end

  def about
  end

  def help
  end

  def impressum
    
  end
  
  def index
    @projects =Project.all
    #Ausgabe von projekten nach done (done=true oder deadline ist vorbei) 
    #und todo (done=false und deadline noch nicht erreicht ).
    #:sorting gibt die Möglichkeit zu sortieren in View    
    if params[:sorting]
      @done = Project.where("done = ? OR deadline < ?", true, Date.today).order(params[:sorting] => :asc)
      @todo = Project.where("done = ? AND deadline >= ?", false, Date.today).order(params[:sorting] => :asc)
    else 
      @done = Project.where("done = ? OR deadline < ?", true, Date.today).order(deadline: :desc)     
      @todo = Project.where("done = ? AND deadline >= ?", false, Date.today).order(deadline: :asc)
    end

    # Nur wenn User Administrator-status hat, hat Zugang zur Indexseite 
    if current_user.admin != true
      redirect_to :root, alert: 'Only for Admins!'
    end

    # benötigt für Excel und CSV Export
    respond_to do |format|
      format.html
      format.csv { send_data @projects.to_csv }
      format.xls
    end
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
    @ideas = Idea.
    #Ausgabe von Projekten von Eigentümer (aktuell eingeloggter user)
    @userprojects = current_user.projects.all
    @userideas = Project.find(params[:id]).ideas
    @idea = Idea.new
    @creativitycards = Creativitycard.all
    #Ausgabe von Kreativismen, die zum Projekt (ID) gehören
    @projectccard = Project.find(params[:id]).creativitycards
  end

  # GET /projects/new
  def new
    @project = Project.new
    @project.ideas.build
    @project.creativitycards.build
  end

  # GET /projects/1/edit
  def edit   
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = current_user.projects.new(project_params)
    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Project was successfully created.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to @project, notice: 'Project was successfully updated.' }
        format.json { render :show, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project
      @project = Project.find(params[:id])
    end

    def set_project_admin_edit_destroy
      @project = Project.find(params[:id])
      # Umleitung zur vorherige Seite, wenn user nicht Admin und Eigentümer des Projekts ist
      if @project.user_id != current_user.id || current_user.admin != true
        redirect_to :back, alert: 'Only Admin are alowd to edit or delete Projects/ You can only change your own Project.'
      end
    end

    def set_project_admin_create
      @project = Project.new
      # Umleitung zur vorherige Seite, wenn User kein Admin-status hat
      if current_user.admin != true
        redirect_to :back, alert: 'Only Admin are alowd to create Projects.'
      end
    end

    def set_user
       @user = current_user
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_params
      params.require(:project).permit(:name, :deadline, :done, :question, :comment, :user_id, creativitycards_attributes: [:id, :title, :suggestion, :example, :shortdescription,  :image, :remote_image_url, :idea_id, :project_id, :user_id,  :_destroy])
    end
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_carousel_creativitycards.html.erb
<!-- Dieser Block wurde ausgeblendet, da Heroku keine Bilder speichert und somit die Bilder nicht im Karousel angezeigt werden. Ersatz bietet den Block darunter. 
  
  <div class="row carousel-holder">
    <div id="carousel-example-generic" class="carousel slide" data-ride="carousel" >      
    <ol class="carousel-indicators">
    	<% @creativitycards.each do |c| %>
        <li class="" data-slide-to="0" data-target="#carousel-example-generic"></li>
        <% end %>
    </ol>
      <div class="carousel-inner">
  			<% @creativitycards.each do |c| %>
        <div class="item">
          <h3><%= c.title %></h3>									    
              <a class="menue">
              <%= image_tag c.image_url(:thumb2) if c.image? %>
              <span><%= image_tag c.image_url(:thumb) if c.image? %></span></a>
          <p style="white-space: pre-line;">
            <%= c.shortdescription %>
					</p>
        </div>
        <% end %>
        <div class="item active">
          <h3>Kreativismen</h3>
					<p >
					    Die Kreativismen sind eine Sammlung von Kreativitätsmethoden von Dr. Roland Müller und Katja Thoring. Die hier gezeigten Kreativismenkarten sollen dabei helfen, entfernte Assoziationen ans Tagelicht bringen und somit für innovative Ideen sorgen. 
					</p>
        </div>
      </div>

      <a class="left carousel-control" data-slide="prev" href="#carousel-example-generic"></a>
      <a class="right carousel-control" data-slide="next" href="#carousel-example-generic"></a> 
    </div>
	</div>
-->


  <div class="row carousel-holder">
    <div id="carousel-example-generic" class="carousel slide" data-ride="carousel" >      
        <ol class="carousel-indicators">
            <li class="" data-slide-to="0" data-target="#carousel-example-generic"></li>
            <li class="" data-slide-to="1" data-target="#carousel-example-generic"></li>
            <li class="active" data-slide-to="2" data-target="#carousel-example-generic"></li>
            <li class="active" data-slide-to="3" data-target="#carousel-example-generic"></li>
            <li class="active" data-slide-to="4" data-target="#carousel-example-generic"></li>
            <li class="active" data-slide-to="5" data-target="#carousel-example-generic"></li>
            <li class="active" data-slide-to="6" data-target="#carousel-example-generic"></li>
            <li class="active" data-slide-to="7" data-target="#carousel-example-generic"></li>
            <li class="active" data-slide-to="8" data-target="#carousel-example-generic"></li>
            <li class="active" data-slide-to="9" data-target="#carousel-example-generic"></li>
            <li class="active" data-slide-to="10" data-target="#carousel-example-generic"></li>
            <li class="active" data-slide-to="11" data-target="#carousel-example-generic"></li>
            <li class="active" data-slide-to="12" data-target="#carousel-example-generic"></li>
            <li class="active" data-slide-to="13" data-target="#carousel-example-generic"></li>
        </ol> </br>
      <div class="carousel-inner">
        <%= render "kreativismen_short" %>
        <div class="item active">
          <h3>Kreativismen</h3>
          <p >
              Die Kreativismen sind eine Sammlung von Kreativitätsmethoden von Dr. Roland Müller und Katja Thoring. Die hier gezeigten Kreativismenkarten sollen dabei helfen, entfernte Assoziationen ans Tagelicht bringen und somit für innovative Ideen sorgen. 
          </p>
        </div>
      </div>

      <a class="left carousel-control" data-slide="prev" href="#carousel-example-generic"></a>
      <a class="right carousel-control" data-slide="next" href="#carousel-example-generic"></a> 
    </div>
  </div>

app/views/projects/_form.html.erb
<%= nested_form_for @project, :html => { :multipart => true} do |f| %> 


  <% if @project.errors.any? %>
    <div class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@project.errors.count, "error") %> prohibited this project from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
          <% @project.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="checkbox">
    <label>
      <%= f.check_box :done %> <%= f.label :done %>
    </label>
  </div>
  <div class="form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name, class: "form-control", placeholder: "Name of Project" %>
  </div>
  <div class="form-group">
    <%= f.label :deadline %><br>
    <%= f.date_field :deadline, class: "form-control", placeholder: "Deadline of Project" %>
  </div>
  <div class="form-group">
    <%= f.label :question %><br>
    <%= f.text_field :question, class: "form-control", placeholder: "Question for Brainstorming" %>
  </div>
  <div class="form-group">
    <%= f.label :comment %><br>
    <%= f.text_area :comment, class: "form-control", placeholder: "some description" %>
  </div>

<!-- 
  Block ermöglicht Kreativismen für Projekt zu erzeugen
-->
  <div class="form-group"> 
    <%= f.fields_for :creativitycards do |builder| %>
    <%= render 'kreativismen', f: builder %>
    <% end %>
    </br>
    <p><%= f.link_to_add "Add more Kreativismen", :creativitycards, class: "btn btn-success btn-sm" %></p>
  </div>   


  <div class="actions">
    <%= f.submit "Save Project", class: "btn btn-primary" %>  
    <%= link_to 'Back to Project overview', projects_path, class: "btn btn-default" %>
  </div> 
<% end %>

app/views/projects/_idea_input.html.erb
<!-- 
Ideefeld
-->
<%= form_for @idea, :html => { :role => "form"} do |f| %>        
  <%= f.text_area :post, :size => "25x10", :maxlength => 300, class: "form-control", placeholder: "Can't wait for your Idea, but only 300 Characters per Idea" %>
  <%= f.hidden_field :project_id, { :value => @project.id } %>
  <%= f.hidden_field :user_id, { :value => current_user.id} %>           
  <%= f.submit "Save Idea", class: "btn btn-info btn-sm btn-block" %>
<% end %> 

app/views/projects/_kreativismen.html.erb
<!-- Erstellung von Kreativismen mithilfe von gem 'nested_form' -->
<div class="panel panel-info">
  <div class="panel-body">
    <%= f.link_to_remove "Remove Kreativismen", class: "btn btn-danger btn-sm" %>
  <div class="field">
  	<%= f.label :title %><br>
    <%= f.text_field :title, class: "form-control" %>    
    <%= f.label :shortdescription %><br>
    <%= f.text_area :shortdescription, class: "form-control" %>
    <%= f.label :suggestion %><br>
    <%= f.text_area :suggestion, class: "form-control" %>
    <%= f.label :example %><br>
    <%= f.text_area :example, class: "form-control" %>

    <%= f.label :"Add Image" %><br>
    <%= f.file_field :image  %>

    <%= f.hidden_field :project_id, { :value => @project.id } %>
    <%= f.hidden_field :user_id, { :value => current_user.id} %> 
  </div>
  </div> 
</div> 

app/views/projects/_kreativismen_short.html.erb

        <div class="item">                         
          <h3>Addieren</h3>
          <a class="menue">
            <%= image_tag ("Addieren.png") %>
            <span><%= image_tag ("Addieren.png") %></span></a>
          <p style="white-space: pre-line;">Mischen, zusammenfügen, verbinden. Aus zwei mach eins. </p>
        </div>                  
 
        <div class="item"> 
          <h3>Analogie</h3>
          <a class="menue">
            <%= image_tag ("Analogie.png") %>
            <span><%= image_tag ("Analogie.png") %></span></a>
          <p style="white-space: pre-line;">Vergleiche ziehen. Funktionsgleiche Strukturen übernehmen. Vorbilder suchen. </p>
        </div>                  
     
        <div class="item"> 
          <h3>Entgeneralisierer</h3>
          <a class="menue">
            <%= image_tag ("Entgeneralisierer.png") %>
            <span><%= image_tag ("Entgeneralisierer.png") %></span></a>
          <p style="white-space: pre-line;">Vorurteile aufheben. Gegebenes in Frage stellen. Kann man etwas, das schon immer so war, auch anders machen? </p>
        </div>                  

        <div class="item"> 
          <h3>Extrem</h3>
          <a class="menue">
            <%= image_tag ("Extrem.png") %>
            <span><%= image_tag ("Extrem.png") %></span></a>
          <p style="white-space: pre-line;"> Bestehende Merkmale ins Extreme ziehen. Mut zu extremen Ideen. Regen alle Regeln verstoßen.</p>
        </div>                  
           

        <div class="item"> 
          <h3>Fokus</h3>
          <a class="menue">
            <%= image_tag ("Fokus.png") %>
            <span><%= image_tag ("Fokus.png") %></span></a>
          <p style="white-space: pre-line;">Akzente setzen. Fokus verlagern. Exzenter. Sich auf das Wesentliche konzentrieren.</p>
        </div>                  

        <div class="item">  
          <h3>Fragment</h3>
          <a class="menue">
            <%= image_tag ("Fragment.png") %>
            <span><%= image_tag ("Fragment.png") %></span></a>
          <p style="white-space: pre-line;">Problem in Teilprobleme zerlegen, diese einzeln bearbeiten, später zusammenfügen.</p>
        </div>                  

        <div class="item"> 
          <h3>Modify</h3>
          <a class="menue">
            <%= image_tag ("Modify.png") %>
            <span><%= image_tag ("Modify.png") %></span></a>
          <p style="white-space: pre-line;"> Welche Eigenschaften kann man ändern? Wie verändert sich dadurch der Charakter, die Funktion des Objekts? Transformieren.</p>
        </div>                  

        <div class="item"> 
          <h3>Perspektive</h3>
          <a class="menue">
            <%= image_tag ("Perspektive.png") %>
            <span><%= image_tag ("Perspektive.png") %></span></a>
          <p style="white-space: pre-line;">Neue Sicht auf die Dinge. Nicht nur den eigenen Standpunkt bedenken. In andere hineinversetzen. Ungewohnte, extreme oder falsche Perspektive erzeugen. </p>
        </div>                  

        <div class="item"> 
          <h3>Prognose</h3>
          <a class="menue">
            <%= image_tag ("Prognose.png") %>
            <span><%= image_tag ("Prognose.png") %></span></a>
          <p style="white-space: pre-line;">Risiken und Chancen antizipieren. Welche Entwicklungen wird es geben? Diesen voraus sein. </p>
        </div>                  

        <div class="item"> 
          <h3>Reduce</h3>
          <a class="menue">
            <%= image_tag ("Reduce.png") %>
            <span><%= image_tag ("Reduce.png") %></span></a>
          <p style="white-space: pre-line;">Weniger ist mehr.</p>
        </div>                  

        <div class="item"> 
          <h3>Szenario</h3>
          <a class="menue">
            <%= image_tag ("Szenario.png") %>
            <span><%= image_tag ("Szenario.png") %></span></a>
          <p style="white-space: pre-line;">Objekt in einen inhaltlichen Kontext setzen. Eine Geschichte um das Objekt erfinden. Was wäre wenn … ? </p>
        </div>                  

        <div class="item"> 
          <h3>Transfer</h3>
          <a class="menue">
            <%= image_tag ("Transfer.png") %>
            <span><%= image_tag ("Transfer.png") %></span></a>
          <p style="white-space: pre-line;"> Idee auf anderen Ort, andere Situation übertragen. Innerhalb eines Mediums bleiben oder zwischen den Disziplinen wechseln. </p>
        </div>                  

        <div class="item"> 
          <h3>Variation</h3>
          <a class="menue">
            <%= image_tag ("Variation.png") %>
            <span><%= image_tag ("Variation.png") %></span></a>
          <p style="white-space: pre-line;"> Welche Optionen gibt es? Von einer Idee ausgehend verschiedene Varianten ableiten. </p>
        </div>                  

        <div class="item"> 
          <h3>Zoom</h3>
          <a class="menue">
            <%= image_tag ("Zoom.png") %>
            <span><%= image_tag ("Zoom.png") %></span></a>
          <p style="white-space: pre-line;">Ist die Idee skalierbar?. Vom Kleinen ins Große ins Kleine. Inhaltlichen Kontext ausweiten.</p>
        </div>                  

app/views/projects/_tab_myIdeas.html.erb
</br>

<div class="row">
  <% @userideas.order(created_at: :desc).each do |idea| %>
    <% if idea.user_id == current_user.id %>
      <div class="col-md-4">
        <div class="thumbnail" id="thumb">                                           
          <%= link_to idea.post, edit_idea_path(idea) %>                                   
        </div>
      </div> 
      <% else %>                 
    <% end %>
  <% end %>
</div>

app/views/projects/help.html.erb

<div class="bs-docs-section">
  <div class="row">
    <div class="col-md-12">

      <div class="page-header">          
        <h1> Help </h1>
      </div>

      <div class="col-md-3" id="leftCol">
        <div class="well">  
          <div class="panel panel-primary">
            <div class="panel-body">   
            <strong>
            <ul class="nav nav-sidebar">
              <li class="active"><%= link_to "Step by Step", projects_help_path(anchor: "step") %></li>
              <li><%= link_to "Sign-Up", projects_help_path(anchor: "sign-up") %></li>
              <li><%= link_to "Edit Profile", projects_help_path(anchor: "edit") %></li>
              <li><%= link_to "Add idea", projects_help_path(anchor: "add") %></li>
              <li><%= link_to "Umfrage", projects_help_path(anchor: "frage") %></li>
              <li><%= link_to "Logout", projects_help_path(anchor: "logout") %></li>
              <li><%= link_to "Eigene Ideen einsehen", projects_help_path(anchor: "ideen") %></li>
            </ul> 
            </strong>
            </div>
          </div>
        </div>
      </div>     

      <div class="col-md-9" id="rightCol"> 
        <div class="well"> 
          <div class="panel panel-primary">
            <h3>Step by Step</h3>
            <div class="panel-body"> 
              <div id="step">                   
                <ol><strong>
                  <li><%= link_to "Sign-Up", projects_help_path(anchor: "sign-up") %></li>
                  <li><%= link_to "Edit Profile", projects_help_path(anchor: "edit") %></li>
                  <li><%= link_to "Add idea", projects_help_path(anchor: "add") %></li>
                  <li><%= link_to "Fragebogen ausfüllen/ändern", projects_help_path(anchor: "frage") %></li>
                  <li><%= link_to "Logout", projects_help_path(anchor: "logout") %></li>
                </strong></ol>
              </div>
            </div>
          </div>
          </br>
          </br>
          <div class="panel panel-primary">
            <div class="panel-body"> 
              <h3>Hilfe</h3>
              <div id="sign-up">
                <br>
                <br>
                <h4>1. Sign-Up</h4>
                <p>Der username muss nicht Ihr tatsächlicher Name sein, sie können sich einen beliebigen Phantasienamen als virtuelle Identifikation ausdenken.</p>

                <p>Ihre E-Mail, sowie sämtliche anderen Angaben werden selbstverständlich vertraulich behandelt. Eine Weitergabe der Daten erfolgt nicht. Für die Auswertung im Rahmen der Bachelorarbeit, werden sämtliche Daten anonymisiert.</p>

                <p>Bitte wählen Sie ein sicheres Passwort mit Buchstaben, Zahlen und Sonderzeichen. Am besten notieren Sie ihr Passwort, da derzeit leider noch keine Passwortwiederherstellung implementiert ist. Administratoren können aus Sicherheitsgründen keine neuen Passwörter für Sie vergeben, da Sie selbst keinen Zugriff auf Ihre Nutzerkonten haben.</p>
              </div>

              <div id="edit">
                <br>
                <br>
                <h4>2. Edit Profile</h4>
                <p>Bitte geben Sie weitere Details zu Ihrer Person an um eine genauere Auswertung zu ermöglichen. Die Daten werden vertraulich behandelt und nur anonymisiert ausgewertet. In einigen der Felder können Sie aus einer Drop-Down Liste den zutreffenden Eintrag auswählen, bei anderen haben Sie die Möglichkeit eine freie Eingabe zu tätigen.</p>

                <p>Am Ende des Formulars wird zur Authentifizierung Ihr aktuelles Passwort benötigt</p>.
                <p>Auf der rechten Seite können Sie optional auch Ihr Passwort ändern.</p>
              </div>

              <div id="add">
                <br>
                <br>
                <h4>3. Add idea</h4>
                <p>Wählen Sie in der Navigation in der Kopfzeile den Reiter Add Ideas aus. Sie gelangen zur Projektübersicht.</p>

                <p>Nun wählen Sie bitte nacheinander Projekt 1 und später Projekt 2 aus. Sie gelangen in die jeweilige Einzelansicht.</p>

                <p>Anschließend finden Sie in der linken unteren Ecke das Fenster um neue Ideen einzutragen. Bitte beschränken Sie sich auf maximal 300 Zeichen um die Ideen übersichtlich zu halten. Vergewissern Sie sich bitte ferner, dass Sie tatsächlich eine Eingabe getätigt haben, bevor Sie die Idee speichern, da andernfalls eine Fehlermeldung ausgegeben wird. In diesem Fall können Sie einfach im Browser die „zurück“ Navigation benutzen. Wenn Sie mit einer Idee zufrieden sind betätigen Sie einfach den „Save Idea“ Button. Sie können diesen Vorgang beliebig oft wiederholen.</p>

                <p>Falls Sie Schwierigkeiten haben, eine Idee zu finden können Sie im Fenster Ideas auf den Reiter all Ideas  wechseln und sich die Ideen anderer Teilnehmer ausgeben lassen. Anschließend können Sie von diesen inspirieren lassen, diese weiterentwickeln oder kombinieren.</p>

                <p>Im Reiter my Ideas können Sie falls es tatsächlich notwendig wird auch Ihre bereits eingegebenen Ideen abändern. Klicken Sie dazu einfach auf den Text einer Ihrer Ideen. Allerdings können Sie eine geänderte Idee auch einfach als neue Idee eingeben, dies ist sogar ausdrücklich erwünscht, denn es gibt wie gesagt keine unsinnigen Ideen ;-) Diese Option ist eher zur Fehlerkorrektur angedacht.</p>

                <p>Eine weitere Inspirationsquelle finden Sie in der linken oberen Ecke. Dort werden Ihnen in einer Karussell-Box verschiedene sogenannter Kreativismen vorgeschlagen. Dabei handelt es sich um Vorschläge kreativer Vorgehensweisen um zum Beispiel Denkblockaden zu lösen oder entferntere Assoziationen ans Tageslicht zu bringen. Wenn Sie einer der Kreativismen anspricht versuchen Sie es doch einfach einmal, die Beschreibung finden Sie direkt in der Box. Falls Sie nähere Informationen wünschen wählen Sie bitte den Hauptnavigationsreiter (Kopfzeile) Kreativismen an. Dort finden Sie die Liste sämtlicher vorgeschlagener Kreativismen.</p>
              </div>

              <div id="frage">
                <br>
                <br>
                <h4>4. Umfrage</h4>
                <p>Wenn Sie für beide Projekte Ideen eingebracht haben, nehmen Sie sich doch bitte noch die Zeit, eine kurze Auswertung der Anwendung vorzunehmen. Zu diesem Zweck wählen Sie einfach den Hauptnavigationsreiter (Kopfzeile) Umfrage an. Sie werden zu einer Umfrage weitergeleitet. Diese soll helfen die Anwendung zu verbessern und die Ergebnisse die sie hervorbringt besser zu verstehen. </p>
                <p><strong> Falls sie bereits einen Fragebogen ausgefüllt haben und diesen ändern wollen, klicken sie bitte auf EDIT (dieser Button erscheint erst, wenn Sie bereits einen Fragebogen ausgefüllt haben) </strong></p>

                <% @user.questions.order(created_at: :desc).each do |question| %>
                  <%= link_to "Edit", edit_question_path(question), class: "btn btn-warning btn-sm" %>
                <% end %> 
              </div>

              <div id="logout">
                <br>
                <br>
                <h4>5. Logout</h4>
                <p>Bitte denken Sie zu Ihrer Sicherheit daran sich am Ende ihrer Sitzung abzumelden, den entsprechenden Button finden Sie oben rechts auf der Hauptnavigationsleiste (Kopfzeile).</p>
              </div> 

              <div id="ideen">
                <br>
                <br>
                <h4>6. eigene Ideen einsehen</h4>
                <p>Die Untersuchung findet in 3 Durchläufen statt. Daher können Sie Ihre Ideen nur innerhalb der angegebenen Deadline einsehen. Zwischenzeitlich besteht diese Möglichkeit nicht. Am Ende der Untersuchung können Sie Ihre Ideen aber wieder einsehen. Bitte nehmen Sie nur an einem der Durchläufe teil um die Ergebnisse nicht zu verfälschen. Eingaben in nachfolgenden Durchläufen können nicht berücksichtigt werden. </p>
              </div>
            </div>
          </div>         
        </div>
      </div>

    </div>
  </div>
</div>

app/views/projects/index.html.erb
<div class="bs-docs-section">
  <div class="row">
    <div class="col-md-12">

      <div class="page-header">          
        <h1>Projects</h1>
      </div>

      <div class="col-md-3" id="leftCol">
        <div class="well">
          <div class="panel panel-primary">
            <div class="panel-body">     
              <p><strong>Wählen Sie bitte einen Projekt aus, um Ideen einzugeben.</strong></p>
            </div>
          </div>
        </div>
      </div>     

      <div class="col-md-9" id="rightCol"> 
        <div class="well"> 
          <%= link_to 'New Project', new_project_path, class: "btn btn-success btn-sm" %>  
          <%= link_to 'Export XLS', url_for(:format => 'xls'), class: "btn btn-primary btn-sm" %> 
          <%= link_to 'Export CSV', url_for(:format => 'csv'), class: "btn btn-primary btn-sm" %>
        </br>
        </br>
          <div class="panel panel-primary">
            <h3>To do </br><small><%= pluralize(@todo.count, "Project") %></small></h3>
            <div class="panel-body">
              <div class="table-responsive table-scrollable">                
                <%= render partial: "projecttable", locals: {projects: @todo, css_class: "todo"} %>
              </div>
            </div>
          </div>
          </br>

          <div class="panel panel-primary">
            <h3>Done</br><small><%= pluralize(@done.count, "Project") %></small></h3>
            <div class="panel-body">
              <div class="table-responsive table-scrollable">                
                <%= render partial: "projecttable", locals: {projects: @done, css_class: "done"} %>
              </div>
            </div>
          </div>                        
        </div>
      </div>

    </div>
  </div>
</div>

app/views/projects/new.js.erb
$('#new_link').hide().after('<%= j render("form") %>');
$('#project_name').focus();
$('#cancel_button').clickCancelButton();